import { RUNNING_CHANCES } from '../battingEvents'
import type { ScenarioNode } from '../scenario'

const FOLLOW_UP_EVENTS = ['single', 'double', 'walk', 'hitByPitch', 'strikeout', 'groundOut', 'flyOut'] as const

export const EMPTY_BASES_SINGLE_NODES: Record<string, ScenarioNode> = {
  'hit.single.resolve': {
    id: 'hit.single.resolve',
    type: 'event',
    view: 'runner:first',
    title: '1루타',
    effects: [
      { type: 'placeRunner', base: 1 },
      { type: 'setPlayerBase', value: 1 },
      { type: 'addHits', value: 1 },
      { type: 'record', message: '1루타' },
      { type: 'announce', title: '1루타 성공!', detail: '1루에 도착했습니다.' },
    ],
    transition: { to: 'single.outfield.check' },
  },
  'single.outfield.check': {
    id: 'single.outfield.check',
    type: 'chance',
    view: 'runner:first',
    title: '외야 수비 판정',
    outcomes: [
      { id: 'clearDrop', label: '명백하게 완전히 뒤로 빠뜨림', weight: RUNNING_CHANCES.outfieldDropClear, transition: { to: 'runner.first.clearDrop.decide', effects: [{ type: 'record', message: '외야수 공 완전 빠뜨림', showInCompletion: false }, { type: 'announce', title: '외야수가 타구를 뒤로 빠뜨렸습니다!', detail: '완전히 뒤로 빠졌습니다. 확실하게 진루할 수 있습니다.' }] } },
      { id: 'ambiguousDrop', label: '애매하게 뒤로 빠뜨림', weight: RUNNING_CHANCES.outfieldDropAmbiguous, transition: { to: 'runner.first.ambiguousDrop.decide', effects: [{ type: 'record', message: '외야수 공 애매하게 빠뜨림', showInCompletion: false }, { type: 'announce', title: '외야수가 타구를 뒤로 빠뜨렸습니다!', detail: '애매하게 빠졌습니다. 진루를 시도하다가 아웃될 수도 있습니다.', tone: 'caution' }] } },
      { id: 'normalFielding', label: '정상 수비', weight: 1 - RUNNING_CHANCES.outfieldDropClear - RUNNING_CHANCES.outfieldDropAmbiguous, transition: { to: 'runner.route' } },
    ],
  },
  'runner.first.clearDrop.decide': {
    id: 'runner.first.clearDrop.decide',
    type: 'choice',
    view: 'runner:first',
    title: '외야수 실책',
    tags: ['surprise-event'],
    description: '1루 주자: 주루 방침을 선택하세요.',
    choices: [
      { id: 'stayFirst', label: '안전하게 1루에 머문다', transition: { to: 'runner.route', effects: [{ type: 'record', message: '외야수 실책, 진루하지 않음', showInCompletion: false }, { type: 'announce', title: '외야수 실책이 나왔지만 진루하지 않았습니다.', detail: '명백히 진루 가능한 찬스를 놓쳤습니다.', tone: 'negative' }] } },
      { id: 'advanceSecond', label: '2루로 진루한다', description: '완전히 뒤로 빠진 타구 · 성공률 100%', transition: { to: 'runner.route', effects: [{ type: 'movePlayer', to: 2 }, { type: 'record', message: '외야 실책 이용, 2루 진루', showInCompletion: false }, { type: 'announce', title: '2루 진루 성공!', detail: '외야수 실책을 이용해 2루에 도착했습니다.' }] } },
    ],
  },
  'runner.first.ambiguousDrop.decide': {
    id: 'runner.first.ambiguousDrop.decide',
    type: 'choice',
    view: 'runner:first',
    title: '외야수 실책',
    tags: ['surprise-event'],
    description: '1루 주자: 주루 방침을 선택하세요.',
    choices: [
      { id: 'stayFirst', label: '안전하게 1루에 머문다', transition: { to: 'runner.route', effects: [{ type: 'record', message: '외야수 실책, 진루하지 않음', showInCompletion: false }, { type: 'announce', title: '외야수 실책이 나왔지만 진루하지 않았습니다.', detail: '위험하다고 판단하여 진루하지 않았습니다.' }] } },
      { id: 'advanceSecond', label: '2루로 진루한다', description: `애매한 타구 · 성공률 ${Math.round(RUNNING_CHANCES.advanceOnAmbiguousDrop * 100)}%`, transition: { to: 'runner.first.ambiguousDrop.advance' } },
    ],
  },
  'runner.first.ambiguousDrop.advance': {
    id: 'runner.first.ambiguousDrop.advance',
    type: 'chance',
    view: 'runner:first',
    title: '2루 진루',
    outcomes: [
      { id: 'success', label: '2루 진루 성공', weight: RUNNING_CHANCES.advanceOnAmbiguousDrop, transition: { to: 'runner.route', effects: [{ type: 'movePlayer', to: 2 }, { type: 'record', message: '외야 실책 이용, 2루 진루 성공', showInCompletion: false }, { type: 'announce', title: '2루 진루 성공!', detail: '위험을 감수하고 추가 진루에 성공했습니다.', tone: 'positive' }] } },
      { id: 'out', label: '2루 진루 실패', weight: 1 - RUNNING_CHANCES.advanceOnAmbiguousDrop, transition: { to: 'plate.complete', effects: [{ type: 'movePlayer', to: 'out' }, { type: 'record', message: '외야 실책 이용, 2루 진루 실패', showInCompletion: false }, { type: 'announce', title: '2루 진루 실패', detail: '2루에서 아웃되었습니다.', tone: 'negative' }] } },
    ],
  },
  'runner.route': {
    id: 'runner.route',
    type: 'router',
    view: 'result',
    title: '주자 위치 확인',
    tags: ['bounded-loop'],
    routes: [
      { to: 'plate.complete', when: [{ field: 'outs', operator: 'gte', value: 3 }] },
      { to: 'plate.complete', when: [{ field: 'playerBase', operator: 'eq', value: null }] },
      { to: 'runner.first.decide', when: [{ field: 'playerBase', operator: 'eq', value: 1 }] },
      { to: 'runner.second.decide', when: [{ field: 'playerBase', operator: 'eq', value: 2 }] },
      { to: 'runner.third.decide', when: [{ field: 'playerBase', operator: 'eq', value: 3 }] },
    ],
  },
  'runner.first.decide': {
    id: 'runner.first.decide',
    type: 'choice',
    view: 'runner:first',
    title: '1루 주자 시점',
    description: '1루 주자: 주루 방침을 선택하세요.',
    choices: [
      { id: 'waitForBatter', label: '1루에 머물면서 타격을 기다린다', description: '후속 타자의 타격 결과를 확인한다', transition: { to: 'wildPitch.check' } },
      { id: 'stealSecond', label: '2루 도루를 시도한다', description: `성공률 ${Math.round(RUNNING_CHANCES.stealSecond * 100)}%`, when: [{ field: 'bases', operator: 'excludes', value: [2] }], transition: { to: 'runner.first.stealSecond' } },
    ],
  },
  'runner.first.stealSecond': {
    id: 'runner.first.stealSecond',
    type: 'chance',
    view: 'runner:first',
    title: '2루 도루',
    outcomes: [
      { id: 'success', label: '2루 도루 성공', weight: RUNNING_CHANCES.stealSecond, transition: { to: 'runner.route', effects: [{ type: 'movePlayer', to: 2 }, { type: 'record', message: '2루 도루 성공' }, { type: 'announce', title: '2루 도루 성공!', detail: '2루에 도착했습니다.' }] } },
      { id: 'out', label: '2루 도루 실패', weight: 1 - RUNNING_CHANCES.stealSecond, transition: { to: 'plate.complete', effects: [{ type: 'movePlayer', to: 'out' }, { type: 'record', message: '2루 도루 실패' }, { type: 'announce', title: '2루 도루 실패', detail: '2루에서 아웃되었습니다.', tone: 'negative' }] } },
    ],
  },
  'runner.second.decide': {
    id: 'runner.second.decide',
    type: 'choice',
    view: 'runner:second',
    title: '2루 주자 시점',
    description: '2루 주자: 주루 방침을 선택하세요.',
    choices: [
      { id: 'waitForBatter', label: '2루에 머물면서 타격을 기다린다', description: '후속 타자의 타격 결과를 확인한다', transition: { to: 'wildPitch.check' } },
      { id: 'stealThird', label: '3루 도루를 시도한다', description: `성공률 ${Math.round(RUNNING_CHANCES.stealThird * 100)}%`, when: [{ field: 'bases', operator: 'excludes', value: [3] }], transition: { to: 'runner.second.stealThird' } },
    ],
  },
  'runner.second.stealThird': {
    id: 'runner.second.stealThird',
    type: 'chance',
    view: 'runner:second',
    title: '3루 도루',
    outcomes: [
      { id: 'success', label: '3루 도루 성공', weight: RUNNING_CHANCES.stealThird, transition: { to: 'runner.route', effects: [{ type: 'movePlayer', to: 3 }, { type: 'record', message: '3루 도루 성공' }, { type: 'announce', title: '3루 도루 성공!', detail: '3루에 도착했습니다.' }] } },
      { id: 'out', label: '3루 도루 실패', weight: 1 - RUNNING_CHANCES.stealThird, transition: { to: 'plate.complete', effects: [{ type: 'movePlayer', to: 'out' }, { type: 'record', message: '3루 도루 실패' }, { type: 'announce', title: '3루 도루 실패', detail: '3루에서 아웃되었습니다.', tone: 'negative' }] } },
    ],
  },
  'runner.third.decide': {
    id: 'runner.third.decide',
    type: 'choice',
    view: 'runner:third',
    title: '3루 주자 시점',
    description: '3루 주자: 주루 방침을 선택하세요.',
    choices: [
      { id: 'waitForBatter', label: '3루에 머물면서 타격을 기다린다', description: '후속 타자의 타격 결과를 확인한다', transition: { to: 'wildPitch.check' } },
    ],
  },
  'wildPitch.check': {
    id: 'wildPitch.check',
    type: 'chance',
    view: 'runner:first',
    title: '폭투 판정',
    outcomes: [
      { id: 'clearWildPitch', label: '명백한 폭투', weight: RUNNING_CHANCES.wildPitchClear, transition: { to: 'runner.wildPitch.clear.decide', effects: [{ type: 'record', message: '포수 뒤로 공이 완전히 빠짐', showInCompletion: false }, { type: 'announce', title: '포수가 공을 뒤로 빠뜨렸습니다!', detail: '완전히 뒤로 빠졌습니다. 확실하게 진루할 수 있습니다.' }] } },
      { id: 'ambiguousWildPitch', label: '애매한 폭투', weight: RUNNING_CHANCES.wildPitchAmbiguous, transition: { to: 'runner.wildPitch.ambiguous.decide', effects: [{ type: 'record', message: '포수 뒤로 공이 애매하게 빠짐', showInCompletion: false }, { type: 'announce', title: '포수가 공을 뒤로 빠뜨렸습니다!', detail: '애매하게 빠졌습니다. 진루를 시도하다가 아웃될 수도 있습니다.', tone: 'caution' }] } },
      { id: 'normalPitch', label: '정상 포구', weight: 1 - RUNNING_CHANCES.wildPitchClear - RUNNING_CHANCES.wildPitchAmbiguous, transition: { to: 'followUp.batting.resolve' } },
    ],
  },
  'runner.wildPitch.clear.decide': {
    id: 'runner.wildPitch.clear.decide',
    type: 'choice',
    view: 'runner:first',
    title: '폭투',
    tags: ['surprise-event', 'player-position-view'],
    description: '주루 방침을 선택하세요.',
    choices: [
      { id: 'stayOnBase', label: '안전하게 현재 베이스에 머문다', transition: { to: 'runner.route', effects: [{ type: 'record', message: '폭투, 진루하지 않음', showInCompletion: false }, { type: 'announce', title: '폭투가 나왔지만 진루하지 않았습니다.', detail: '명백히 진루 가능한 찬스를 놓쳤습니다.', tone: 'negative' }] } },
      { id: 'advance', label: '다음 베이스로 진루한다', description: '폭투를 이용한다 · 성공률 100%', transition: { to: 'runner.route', effects: [{ type: 'advancePlayer' }, { type: 'record', message: '폭투 이용 진루 성공', showInCompletion: false }, { type: 'announcePlayerAdvance', title: '폭투 진루 성공!', detail: '다음 베이스에 도착했습니다.' }] } },
    ],
  },
  'runner.wildPitch.ambiguous.decide': {
    id: 'runner.wildPitch.ambiguous.decide',
    type: 'choice',
    view: 'runner:first',
    title: '폭투',
    tags: ['surprise-event', 'player-position-view'],
    description: '주루 방침을 선택하세요.',
    choices: [
      { id: 'stayOnBase', label: '안전하게 현재 베이스에 머문다', transition: { to: 'runner.route', effects: [{ type: 'record', message: '폭투, 진루하지 않음', showInCompletion: false }, { type: 'announce', title: '폭투가 나왔지만 진루하지 않았습니다.', detail: '위험하다고 판단하여 진루하지 않았습니다.' }] } },
      { id: 'advance', label: '다음 베이스로 진루한다', description: `폭투를 이용한다 · 성공률 ${Math.round(RUNNING_CHANCES.advanceOnAmbiguousWildPitch * 100)}%`, transition: { to: 'runner.wildPitch.ambiguous.advance' } },
    ],
  },
  'runner.wildPitch.ambiguous.advance': {
    id: 'runner.wildPitch.ambiguous.advance',
    type: 'chance',
    view: 'runner:first',
    title: '폭투 진루 판정',
    outcomes: [
      { id: 'success', label: '폭투 진루 성공', weight: RUNNING_CHANCES.advanceOnAmbiguousWildPitch, transition: { to: 'runner.route', effects: [{ type: 'advancePlayer' }, { type: 'record', message: '폭투 이용 진루 성공', showInCompletion: false }, { type: 'announcePlayerAdvance', title: '폭투 진루 성공!', detail: '위험을 감수하고 추가 진루에 성공했습니다.', tone: 'positive' }] } },
      { id: 'out', label: '폭투 진루 실패', weight: 1 - RUNNING_CHANCES.advanceOnAmbiguousWildPitch, transition: { to: 'plate.complete', effects: [{ type: 'movePlayer', to: 'out' }, { type: 'record', message: '폭투 이용 진루 실패', showInCompletion: false }, { type: 'announce', title: '폭투 진루 실패', detail: '다음 베이스에서 아웃되었습니다.', tone: 'negative' }] } },
    ],
  },
  'followUp.batting.resolve': {
    id: 'followUp.batting.resolve',
    type: 'batting',
    view: 'batter',
    title: '후속 타자 결과',
    mode: 'random',
    eventIds: [...FOLLOW_UP_EVENTS],
    routes: [
      { to: 'followUp.ground.check', when: [{ field: 'battingEvent', operator: 'eq', value: 'groundOut' }] },
      { to: 'followUp.batting.apply', when: [{ field: 'battingEvent', operator: 'in', value: [...FOLLOW_UP_EVENTS] }] },
    ],
  },
  'followUp.ground.check': {
    id: 'followUp.ground.check',
    type: 'chance',
    view: 'batter',
    title: '후속 내야 땅볼 수비 판정',
    outcomes: [
      { id: 'fieldingError', label: '내야수 포구 실책', weight: RUNNING_CHANCES.infieldGroundFieldingError, transition: { to: 'followUp.ground.fieldingError' } },
      { id: 'throwingError', label: '내야수 송구 실책', weight: RUNNING_CHANCES.infieldGroundThrowingError, transition: { to: 'followUp.ground.throwingError.check' } },
      { id: 'cleanPlay', label: '내야수 정상 수비', weight: 1 - RUNNING_CHANCES.infieldGroundFieldingError - RUNNING_CHANCES.infieldGroundThrowingError, transition: { to: 'followUp.ground.resolve' } },
    ],
  },
  'followUp.ground.resolve': {
    id: 'followUp.ground.resolve',
    type: 'event',
    view: 'result',
    title: '후속 내야 땅볼 적용',
    effects: [{ type: 'applyFollowUpGroundOut' }],
    transition: { to: 'followUp.ground.route' },
  },
  'followUp.ground.route': {
    id: 'followUp.ground.route',
    type: 'router',
    view: 'result',
    title: '내야 땅볼 주루 확인',
    routes: [
      { to: 'runner.second.groundOut.decide', when: [{ field: 'playerBase', operator: 'eq', value: 2 }] },
      { to: 'runner.route' },
    ],
  },
  'runner.second.groundOut.decide': {
    id: 'runner.second.groundOut.decide',
    type: 'choice',
    view: 'runner:second',
    title: '내야 땅볼 아웃',
    description: '2루 주자: 주루 방침을 선택하세요.',
    choices: [
      { id: 'staySecond', label: '안전하게 2루에 머문다', transition: { to: 'runner.route', effects: [{ type: 'announce', title: '후속 타자 내야 땅볼 아웃', detail: '2루에 머물렀습니다.' }] } },
      { id: 'advanceThird', label: '내야수 송구 순간 3루 진루를 시도한다', description: `성공률 ${Math.round(RUNNING_CHANCES.advanceOnGroundBallToThird * 100)}%`, transition: { to: 'runner.second.groundOut.advance' } },
    ],
  },
  'runner.second.groundOut.advance': {
    id: 'runner.second.groundOut.advance',
    type: 'chance',
    view: 'runner:second',
    title: '3루 진루',
    outcomes: [
      { id: 'success', label: '3루 진루 성공', weight: RUNNING_CHANCES.advanceOnGroundBallToThird, transition: { to: 'runner.route', effects: [{ type: 'movePlayer', to: 3 }, { type: 'record', message: '내야 땅볼 중 3루 진루 성공', showInCompletion: false }, { type: 'announce', title: '후속 타자 내야 땅볼 3루 진루 성공!', detail: '내야수 송구 순간 3루에 도착했습니다.', tone: 'positive' }] } },
      { id: 'out', label: '3루 진루 실패', weight: 1 - RUNNING_CHANCES.advanceOnGroundBallToThird, transition: { to: 'plate.complete', effects: [{ type: 'movePlayer', to: 'out' }, { type: 'record', message: '내야 땅볼 중 3루 진루 실패', showInCompletion: false }, { type: 'announce', title: '후속 타자 내야 땅볼 3루 진루 실패', detail: '3루에서 아웃되었습니다.', tone: 'negative' }] } },
    ],
  },
  'followUp.ground.fieldingError': {
    id: 'followUp.ground.fieldingError',
    type: 'event',
    view: 'runner:first',
    title: '내야수 포구 실책',
    effects: [{ type: 'applyHit', batterTo: 1, creditHit: false }, { type: 'record', message: '후속 타자 내야 땅볼 포구 실책' }, { type: 'announcePlayerAdvance', title: '내야수가 땅볼을 포구 실책했습니다!', detail: '한 베이스 진루했습니다.' }],
    transition: { to: 'runner.route' },
  },
  'followUp.ground.throwingError.check': {
    id: 'followUp.ground.throwingError.check',
    type: 'chance',
    view: 'batter',
    title: '후속 내야 땅볼 1루 송구 판정',
    outcomes: [
      { id: 'clearMiss', label: '명백히 1루수 뒤로 빠진 송구', weight: RUNNING_CHANCES.infieldGroundThrowingErrorClear, transition: { to: 'followUp.ground.throwingError.route', effects: [{ type: 'applyHit', batterTo: 1, creditHit: false }, { type: 'record', message: '후속 타자 내야 땅볼 송구 실책' }, { type: 'setFlag', key: 'groundThrowMiss', value: 'clear' }, { type: 'announcePlayerAdvance', title: '후속 타자: 내야 땅볼 송구 실책!', detail: '1루수 뒤로 송구가 완전히 빠졌습니다. 확실하게 추가 진루할 수 있습니다.' }] } },
      { id: 'ambiguousMiss', label: '애매하게 1루수 뒤로 빠진 송구', weight: RUNNING_CHANCES.infieldGroundThrowingErrorAmbiguous, transition: { to: 'followUp.ground.throwingError.route', effects: [{ type: 'applyHit', batterTo: 1, creditHit: false }, { type: 'record', message: '후속 타자 내야 땅볼 송구 실책' }, { type: 'setFlag', key: 'groundThrowMiss', value: 'ambiguous' }, { type: 'announcePlayerAdvance', title: '후속 타자: 내야 땅볼 송구 실책!', detail: '1루수 뒤로 송구가 빠졌습니다. 추가 진루를 시도하다가 아웃될 수도 있습니다.', tone: 'caution' }] } },
    ],
  },
  'followUp.ground.throwingError.route': {
    id: 'followUp.ground.throwingError.route',
    type: 'router',
    view: 'result',
    title: '송구 실책 주루 확인',
    routes: [
      { to: 'plate.complete', when: [{ field: 'playerBase', operator: 'eq', value: null }] },
      { to: 'followUp.ground.throwingError.clear.decide', when: [{ field: 'flag', operator: 'eq', key: 'groundThrowMiss', value: 'clear' }] },
      { to: 'followUp.ground.throwingError.ambiguous.decide', when: [{ field: 'flag', operator: 'eq', key: 'groundThrowMiss', value: 'ambiguous' }] },
    ],
  },
  'followUp.ground.throwingError.clear.decide': {
    id: 'followUp.ground.throwingError.clear.decide',
    type: 'choice',
    view: 'runner:first',
    title: '내야 땅볼 송구 실책',
    tags: ['surprise-event', 'player-position-view'],
    description: '주루 방침을 선택하세요.',
    choices: [
      { id: 'stayOnBase', label: '안전하게 현재 베이스에 머문다', transition: { to: 'runner.route', effects: [{ type: 'record', message: '송구 실책, 추가 진루하지 않음', showInCompletion: false }, { type: 'announce', title: '후속 타자 내야 땅볼 송구 실책이 나왔지만 진루하지 않았습니다.', detail: '명백히 진루 가능한 찬스를 놓쳤습니다.', tone: 'negative' }] } },
      { id: 'advance', label: '다음 베이스로 진루한다', description: '1루수 뒤로 완전히 빠진 송구 · 성공률 100%', transition: { to: 'runner.route', effects: [{ type: 'advancePlayer' }, { type: 'record', message: '송구 실책 이용, 추가 진루', showInCompletion: false }, { type: 'announcePlayerAdvance', title: '내야 땅볼 송구 실책 추가 진루 성공!', detail: '후속 타자 내야 땅볼 송구 실책을 이용해 다음 베이스에 도착했습니다.' }] } },
    ],
  },
  'followUp.ground.throwingError.ambiguous.decide': {
    id: 'followUp.ground.throwingError.ambiguous.decide',
    type: 'choice',
    view: 'runner:first',
    title: '내야 땅볼 송구 실책',
    tags: ['surprise-event', 'player-position-view'],
    description: '주루 방침을 선택하세요.',
    choices: [
      { id: 'stayOnBase', label: '안전하게 현재 베이스에 머문다', transition: { to: 'runner.route', effects: [{ type: 'record', message: '송구 실책, 추가 진루하지 않음', showInCompletion: false }, { type: 'announce', title: '후속 타자 내야 땅볼 송구 실책이 나왔지만 진루하지 않았습니다.', detail: '위험하다고 판단하여 진루하지 않았습니다.' }] } },
      { id: 'advance', label: '다음 베이스로 진루한다', description: `애매한 송구 · 성공률 ${Math.round(RUNNING_CHANCES.advanceOnAmbiguousDrop * 100)}%`, transition: { to: 'followUp.ground.throwingError.ambiguous.advance' } },
    ],
  },
  'followUp.ground.throwingError.ambiguous.advance': {
    id: 'followUp.ground.throwingError.ambiguous.advance',
    type: 'chance',
    view: 'runner:first',
    title: '추가 진루',
    tags: ['player-position-view'],
    outcomes: [
      { id: 'success', label: '추가 진루 성공', weight: RUNNING_CHANCES.advanceOnAmbiguousDrop, transition: { to: 'runner.route', effects: [{ type: 'advancePlayer' }, { type: 'record', message: '송구 실책 이용, 추가 진루 성공', showInCompletion: false }, { type: 'announcePlayerAdvance', title: '내야 땅볼 송구 실책 추가 진루 성공!', detail: '위험을 감수하고 추가 진루에 성공했습니다.', tone: 'positive' }] } },
      { id: 'out', label: '추가 진루 실패', weight: 1 - RUNNING_CHANCES.advanceOnAmbiguousDrop, transition: { to: 'plate.complete', effects: [{ type: 'movePlayer', to: 'out' }, { type: 'record', message: '송구 실책 이용, 추가 진루 실패', showInCompletion: false }, { type: 'announce', title: '내야 땅볼 송구 실책 추가 진루 실패', detail: '다음 베이스에서 아웃되었습니다.', tone: 'negative' }] } },
    ],
  },
  'followUp.batting.apply': {
    id: 'followUp.batting.apply',
    type: 'event',
    view: 'result',
    title: '후속 타격 적용',
    effects: [{ type: 'applyBattingEvent' }],
    transition: { to: 'followUp.batting.route' },
  },
  'followUp.batting.route': {
    id: 'followUp.batting.route',
    type: 'router',
    view: 'result',
    title: '후속 타격 주루 확인',
    routes: [
      { to: 'runner.battingAdvance.outfield.check', when: [{ field: 'flag', operator: 'eq', key: 'advancedByFollowUpHit', value: true }] },
      { to: 'runner.route' },
    ],
  },
  'runner.battingAdvance.outfield.check': {
    id: 'runner.battingAdvance.outfield.check',
    type: 'chance',
    view: 'runner:first',
    title: '외야 수비 판정',
    tags: ['player-position-view'],
    outcomes: [
      { id: 'clearDrop', label: '명백하게 완전히 뒤로 빠뜨림', weight: RUNNING_CHANCES.outfieldDropClear, transition: { to: 'runner.battingAdvance.clearDrop.decide', effects: [{ type: 'record', message: '외야수 공 완전 빠뜨림', showInCompletion: false }, { type: 'announceFollowUpOutfieldError', clear: true }] } },
      { id: 'ambiguousDrop', label: '애매하게 뒤로 빠뜨림', weight: RUNNING_CHANCES.outfieldDropAmbiguous, transition: { to: 'runner.battingAdvance.ambiguousDrop.decide', effects: [{ type: 'record', message: '외야수 공 애매하게 빠뜨림', showInCompletion: false }, { type: 'announceFollowUpOutfieldError', clear: false }] } },
      { id: 'normalFielding', label: '정상 수비', weight: 1 - RUNNING_CHANCES.outfieldDropClear - RUNNING_CHANCES.outfieldDropAmbiguous, transition: { to: 'runner.route' } },
    ],
  },
  'runner.battingAdvance.clearDrop.decide': {
    id: 'runner.battingAdvance.clearDrop.decide',
    type: 'choice',
    view: 'runner:first',
    title: '외야수 실책',
    tags: ['surprise-event', 'player-position-view'],
    description: '주루 방침을 선택하세요.',
    choices: [
      { id: 'stayOnBase', label: '안전하게 현재 베이스에 머문다', transition: { to: 'runner.route', effects: [{ type: 'record', message: '외야수 실책, 진루하지 않음', showInCompletion: false }, { type: 'announce', title: '후속 타자 타구 외야수 실책이 나왔지만 진루하지 않았습니다.', detail: '명백히 진루 가능한 찬스를 놓쳤습니다.', tone: 'negative' }] } },
      { id: 'advance', label: '다음 베이스로 진루한다', description: '완전히 뒤로 빠진 타구 · 성공률 100%', transition: { to: 'runner.route', effects: [{ type: 'advancePlayer' }, { type: 'record', message: '외야 실책 이용, 추가 진루', showInCompletion: false }, { type: 'announcePlayerAdvance', title: '후속 타자 타구 외야수 실책 추가 진루 성공!', detail: '외야수 실책을 이용해 다음 베이스에 도착했습니다.' }] } },
    ],
  },
  'runner.battingAdvance.ambiguousDrop.decide': {
    id: 'runner.battingAdvance.ambiguousDrop.decide',
    type: 'choice',
    view: 'runner:first',
    title: '외야수 실책',
    tags: ['surprise-event', 'player-position-view'],
    description: '주루 방침을 선택하세요.',
    choices: [
      { id: 'stayOnBase', label: '안전하게 현재 베이스에 머문다', transition: { to: 'runner.route', effects: [{ type: 'record', message: '외야수 실책, 진루하지 않음', showInCompletion: false }, { type: 'announce', title: '후속 타자 타구 외야수 실책이 나왔지만 진루하지 않았습니다.', detail: '위험하다고 판단하여 진루하지 않았습니다.' }] } },
      { id: 'advance', label: '다음 베이스로 진루한다', description: `애매한 타구 · 성공률 ${Math.round(RUNNING_CHANCES.advanceOnAmbiguousDrop * 100)}%`, transition: { to: 'runner.battingAdvance.ambiguousDrop.advance' } },
    ],
  },
  'runner.battingAdvance.ambiguousDrop.advance': {
    id: 'runner.battingAdvance.ambiguousDrop.advance',
    type: 'chance',
    view: 'runner:first',
    title: '추가 진루',
    tags: ['player-position-view'],
    outcomes: [
      { id: 'success', label: '추가 진루 성공', weight: RUNNING_CHANCES.advanceOnAmbiguousDrop, transition: { to: 'runner.route', effects: [{ type: 'advancePlayer' }, { type: 'record', message: '외야 실책 이용, 추가 진루 성공', showInCompletion: false }, { type: 'announcePlayerAdvance', title: '후속 타자 타구 외야수 실책 추가 진루 성공!', detail: '위험을 감수하고 추가 진루에 성공했습니다.', tone: 'positive' }] } },
      { id: 'out', label: '추가 진루 실패', weight: 1 - RUNNING_CHANCES.advanceOnAmbiguousDrop, transition: { to: 'plate.complete', effects: [{ type: 'movePlayer', to: 'out' }, { type: 'record', message: '외야 실책 이용, 추가 진루 실패', showInCompletion: false }, { type: 'announce', title: '후속 타자 타구 외야수 실책 추가 진루 실패', detail: '다음 베이스에서 아웃되었습니다.', tone: 'negative' }] } },
    ],
  },
  'plate.complete': {
    id: 'plate.complete',
    type: 'terminal',
    view: 'result',
    title: '플레이 완료',
    result: 'plateComplete',
  },
}
